services:

  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

  server:
    build: ./server
    container_name: server_c
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app  
