services:

  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: real_world_app
    ports:
      - "3306:3306"
    volumes:
      - ./server/test/docker/sql_file:/docker-entrypoint-initdb.d



  #server:
  #  build: ./server
  #  container_name: server_c
  #  ports:
  #    - '8080:8080'
  #  volumes:
  #    - ./server:/server
